// Generated by CIRCT firtool-1.135.0
module Decoder(	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/decoder/decoder.scala:8:7
  input  [2:0] io_in,	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/decoder/decoder.scala:9:14
  output [7:0] io_out	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/decoder/decoder.scala:9:14
);

  assign io_out =
    (&io_in)
      ? 8'h80
      : {1'h0,
         io_in == 3'h6
           ? 7'h40
           : {1'h0,
              io_in == 3'h5
                ? 6'h20
                : {1'h0,
                   io_in == 3'h4
                     ? 5'h10
                     : {1'h0,
                        io_in == 3'h3
                          ? 4'h8
                          : {1'h0,
                             io_in == 3'h2
                               ? 3'h4
                               : {1'h0, io_in == 3'h1 ? 2'h2 : 2'h1}}}}}};	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/decoder/decoder.scala:8:7, :14:44
endmodule

module Top(	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  input        clock,	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
               reset,	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  input  [2:0] io_in,	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:13:14
  output [7:0] io_out	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:13:14
);

  Decoder decoder (	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:18:23
    .io_in  (io_in),
    .io_out (io_out)
  );	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:18:23
endmodule


// ----- 8< ----- FILE "verification/layers-Top-Verification.sv" ----- 8< -----

// Generated by CIRCT firtool-1.135.0
`ifndef layers_Top_Verification	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  `define layers_Top_Verification
`endif // not def layers_Top_Verification

// ----- 8< ----- FILE "verification/assert/layers-Top-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.135.0
`ifndef layers_Top_Verification_Assert	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  `define layers_Top_Verification_Assert
  `include "layers-Top-Verification.sv"	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
`endif // not def layers_Top_Verification_Assert

// ----- 8< ----- FILE "verification/assume/layers-Top-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.135.0
`ifndef layers_Top_Verification_Assume	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  `define layers_Top_Verification_Assume
  `include "layers-Top-Verification.sv"	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
`endif // not def layers_Top_Verification_Assume

// ----- 8< ----- FILE "verification/cover/layers-Top-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.135.0
`ifndef layers_Top_Verification_Cover	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
  `define layers_Top_Verification_Cover
  `include "layers-Top-Verification.sv"	// home/lsj/projects/ysyx-pre/prac-mill/src/main/scala/top/top.scala:12:7
`endif // not def layers_Top_Verification_Cover
